name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - v*
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git bash p7zip

    - name: Workaround permission issue
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Compile project
      run: |
        make clean all

    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ steps.slug.outputs.sha8 }}
        path: bin

    - name: Compress & Rename bin folder
      run: |
        mv bin/ ${{ github.event.repository.name }}/
        7z a -t7z ${{ github.event.repository.name }}.7z ${{ github.event.repository.name }}/
 
    - name: Create pre-release
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Development build"
        files: |
               ${{ github.event.repository.name }}.7z

    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ github.event.repository.name }}.7z
        tag_name: ${{ steps.tag.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
